name: geolocator_platform_interface
description: A common platform interface for the geolocator plugin.
homepage: https://github.com/baseflow/flutter-geolocator
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.1.0-nullsafety

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.3.0-nullsafety.3
  plugin_platform_interface: ^1.1.0-nullsafety
  vector_math: ^ 2.1.0-nullsafety.3

dev_dependencies:
  async: ^ 2.5.0-nullsafety.1
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.2
  mockito: ^4.1.3

environment:
  sdk: ">=2.11.0-260.0.dev <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
