# This is a basic workflow to help you get started with Actions

name: Geolocator - App Facing Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Make sure Java is installed on the build machine
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Change into the directory containing the App Facing Package
      - name: Change to App Facing Package
        run: cd $GITHUB_WORKSPACE/geolocator

      # Download all Flutter packages the geolocator depends on
      - name: Download dependencies
        run: flutter pub get
      
      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze
      
      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --converage
      
      # Build Android version of the example app
      - name: Run Android build
        run: flutter build apk -t example/lib/main.dart --release
   
      # Build iOS version of the example app
      - name: Run iOS build
        run: flutter build ios -t example/lib/main.dart --release --no-codesign
